### ISSUE TITLE
pal_coord not found

### ISSUE THREAD

**Issue by jchoo44** [magicbear/palworld-server-toolkit#100]
Trying to run this from the command line.

`python -i -m  palworld_server_toolkit.editor Level.sav`

I have python3.11 installed.

`palworld-server-toolkit\palworld_server_toolkit\editor.py", line 22, in <module>
    import palworld_coord
ModuleNotFoundError: No module named 'palworld_coord'`

**Comment by FunjaPlays** [comment]
Use the exe file
I have No Problems with that

**Comment by magicbear** [comment]
pip install palworld_coord
