### ISSUE TITLE
Delete Damage Instance Error

### ISSUE THREAD

**Issue by alvinHRFM** [magicbear/palworld-server-toolkit#101]
Error occured when EquipItemContainerId->Value->ID->Value is invalid that cannot find OwnerPlayerUID by the GUID. 

Error:
![image](https://github.com/magicbear/palworld-server-toolkit/assets/36674765/ea50cec3-ab3a-4d49-9304-9fe44e7c4649)

Level.sav.json:
![image](https://github.com/magicbear/palworld-server-toolkit/assets/36674765/123c2b4f-a6d2-4c94-875a-f8263c2538f0)

**Comment by magicbear** [comment]
bug fixed on 0.8.5
