### ISSUE TITLE
Error caused by game version update Request update

### ISSUE THREAD

**Issue by Banxiaxiala** [magicbear/palworld-server-toolkit#109]
Traceback (most recent call last):
File "palworld server toolkit\editor.py", line 1613, in
migrate to steamid
File "palworld server toolkit\editor.py", line 3471, in MigratePlayer
File "palworld server toolkit\editor.py", line 201, in
load skipped decode
File "C:\Users\bx1290.8.5\palworld server toolkit\palobject.py", line
1571.in BatchParseltem
File "C:\Users\bx12910.8.5\palworld server toolkit\palobject.py", line
1491,in parse skiped item
File "c:\Users\bx129\0.8.5\palworld server toolkit\palobject.py", line
1066, in property
File "C:Program
Files\Python310vlib\site-packages\palworld save tools\archive.py", line
301, in property
File "C:Program
FileslPython310vlib\site-packages\palworld save tools\rawdata\map o
bject.py", line 45, in decode
map concrete model.decode bytes(
File "C\Program
Files\Python310vlib\site-packages\palworld save tools\rawdatalmap c
oncrete model.py", line 441, in decode bytes
raise Exception(
Exception: Warning: EOF not reached for SphereFactory Black 03
PalMapobjectConvertltemModel: ori:
92810279ddb984428ca62be1643c93743cca7ee6b5d591448d5740fbebdf04
59050000004e6f6e550000000000000000000000804000000000remaining:4
![image](https://github.com/magicbear/palworld-server-toolkit/assets/35516655/27791d22-3450-407a-93f2-664f77fdd5b8)

**Comment by nymphikaros** [comment]
this is coming after the Update of Palworld, if you try to open Item Edit
the Windows keeps Blank 

Exception in thread Thread-3 (load):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "palworld_server_toolkit\editor.py", line 1289, in load
  File "palworld_server_toolkit\editor.py", line 187, in parse_item
  File "palworld_server_toolkit\editor.py", line 187, in parse_item
  File "palworld_server_toolkit\editor.py", line 180, in parse_item
  File "palworld_server_toolkit\palobject.py", line 1491, in parse_skiped_item
  File "palworld_server_toolkit\palobject.py", line 1066, in property
  File "palworld_save_tools\archive.py", line 396, in property
  File "palworld_save_tools\rawdata\item_container.py", line 13, in decode
  File "palworld_save_tools\rawdata\item_container.py", line 30, in decode_bytes
Exception: Warning: EOF not reached

![image](https://github.com/magicbear/palworld-server-toolkit/assets/10379439/1e542a3e-4943-4a46-85a2-124af449096c)

**Comment by kcollins7** [comment]
I think the other utilities that this kit combines are being updated and then mgaicbear will update his eventually.

**Comment by VYRNACH** [comment]
> I think the other utilities that this kit combines are being updated and then mgaicbear will update his eventually.
https://github.com/cheahjs/palworld-save-tools/pull/171
already updated 3 days ago. Anyone working on integrating the changes?

**Comment by kemjensak** [comment]
Works well if you update two submodules
[https://github.com/EternalWraith/PalEdit](https://github.com/EternalWraith/PalEdit)
and
[https://github.com/cheahjs/palworld-save-tools](https://github.com/cheahjs/palworld-save-tools)
![image](https://github.com/magicbear/palworld-server-toolkit/assets/60342784/941bd4f3-3087-4814-935f-f94874979952)

**Comment by nymphikaros** [comment]
> Works well if you update two submodules https://github.com/EternalWraith/PalEdit and https://github.com/cheahjs/palworld-save-tools ![image](https://private-user-images.githubusercontent.com/60342784/320604685-941bd4f3-3087-4814-935f-f94874979952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDI4NDQsIm5iZiI6MTcxMjYwMjU0NCwicGF0aCI6Ii82MDM0Mjc4NC8zMjA2MDQ2ODUtOTQxYmQ0ZjMtMzA4Ny00ODE0LTkzNWYtZjk0ODc0OTc5OTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE4NTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZmQ4ZDgwMzU0YWI5OWQ5YmFjYzFlMDhhMTA4YjVmOWY5NDhkNDA2NDRlMDY3MjU4YjAwNDA4MjlmYWZlM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iPy0umAvrdRTGJBRu9gk9T5_WGANqAGbFzKUZGhKU84)

Can you Tell me how i do it?  Thx for reply

**Comment by jedlarosa** [comment]
> Works well if you update two submodules https://github.com/EternalWraith/PalEdit and https://github.com/cheahjs/palworld-save-tools ![image](https://private-user-images.githubusercontent.com/60342784/320604685-941bd4f3-3087-4814-935f-f94874979952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTI0OTIsIm5iZiI6MTcxMjYxMjE5MiwicGF0aCI6Ii82MDM0Mjc4NC8zMjA2MDQ2ODUtOTQxYmQ0ZjMtMzA4Ny00ODE0LTkzNWYtZjk0ODc0OTc5OTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDIxMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOTRjY2QxYzE2MWY4Y2Q0OTFkZWVmYjY2YWI2MDA3OWFkNjA2MWRjMjY0YjQyMjExNmJmMTc3MWEyNjQ2M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cHyICbdh2BQOnnhmlnbXim3VCQCtzPl8E8hpHcWknNY)

How did you do it please?

**Comment by kemjensak** [comment]
First, clone this repo with submodule
`git clone https://github.com/magicbear/palworld-server-toolkit.git --recurse-submodules`

install required packages
`pip install palworld_coord msgpack pyperclip`

and move to cloned repo
`cd palworld-server-toolkit`

clone another repo
`git clone https://github.com/EternalWraith/PalEdit pal_edit`

update submodule(save_tools)
`git submodule update --remote`

run!
`python3 palworld_server_toolkit/editor.py`

**Comment by seijims** [comment]
> First, clone this repo with submodule `git clone https://github.com/magicbear/palworld-server-toolkit.git --recurse-submodules`
> 
> install required packages `pip install palworld_coord msgpack pyperclip`
> 
> and move to cloned repo `cd palworld-server-toolkit`
> 
> clone another repo `git clone https://github.com/EternalWraith/PalEdit pal_edit`
> 
> update submodule(save_tools) `git submodule update --remote`
> 
> run! `python3 palworld_server_toolkit/editor.py`
> 
> Some command may be missing. so if you got error, plz let me know

@kemjensak 
I tried running the first command in a new python window and got:
  File "<stdin>", line 1
    git clone https://github.com/magicbear/palworld-server-toolkit.git --recurse-submodules
        ^^^^^
SyntaxError: invalid syntax

clone seems to be the invalid syntax
Do I need to run the command in a specific instance of python and if so where/how?
Any help would be appreciated.

**Comment by jedlarosa** [comment]
@kemjensak 
Same. Syntax error. Please send us the correct and specific code structures to execute the command lines.
Thank you!

**Comment by jedlarosa** [comment]
Nevermind. I finally found the issue. Thanks for all your help, @kemjensak!

**Comment by seijims** [comment]
@jedlarosa 
How did you end up getting it to work?

**Comment by seijims** [comment]
so I got everything to work except when I try to run python3 palworld_server_toolkit/editor.py I get:
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by Banxiaxiala** [comment]
同步更新tool 即可正常运行

**Comment by kcollins7** [comment]
> 同步更新tool 即可正常运行

What does this mean?

**Comment by seijims** [comment]
I think they said to "Update the tool synchronously and it will run normally" however I am unsure of how to do that and what "tool" they are referring to. If I had to guess the tool is python but im still unsure of how to update it synchronously

**Comment by Banxiaxiala** [comment]
> I think they said to "Update the tool synchronously and it will run normally" however I am unsure of how to do that and what "tool" they are referring to. If I had to guess the tool is python but im still unsure of how to update it synchronously
https://github.com/cheahjs/palworld-save-tools
The project is put in its place and it will work properly

**Comment by Banxiaxiala** [comment]
> I think they said to "Update the tool synchronously and it will run normally" however I am unsure of how to do that and what "tool" they are referring to. If I had to guess the tool is python but im still unsure of how to update it synchronously



> I think they said to "Update the tool synchronously and it will run normally" however I am unsure of how to do that and what "tool" they are referring to. If I had to guess the tool is python but im still unsure of how to update it synchronously

This project relies on my above-mentioned project

**Comment by kcollins7** [comment]
> > I think they said to "Update the tool synchronously and it will run normally" however I am unsure of how to do that and what "tool" they are referring to. If I had to guess the tool is python but im still unsure of how to update it synchronously
> 
> > I think they said to "Update the tool synchronously and it will run normally" however I am unsure of how to do that and what "tool" they are referring to. If I had to guess the tool is python but im still unsure of how to update it synchronously
> 
> This project relies on my above-mentioned project

So update the dependencies for palworld-server-toolkit in pip as well? Does PalEdit still work though? 

I know that both PalEdit (https://github.com/EternalWraith/PalEdit) and PalCharacterTransfer (https://github.com/jmkl009/PalworldCharacterTransfer) have been updated on github, but they aren't listed as packages in pip that palworld-server-toolkit uses unlike palworld-save-tools. I'm not sure how those get updated without magicbear updating?

**Comment by Banxiaxiala** [comment]
重命名即可 实际内容是相同的




?
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "magicbear/palworld-server-toolkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月12日(星期五) 中午11:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [magicbear/palworld-server-toolkit] Error caused by game version update Request update (Issue #109)





   
I think they said to "Update the tool synchronously and it will run normally" however I am unsure of how to do that and what "tool" they are referring to. If I had to guess the tool is python but im still unsure of how to update it synchronously
   
I think they said to "Update the tool synchronously and it will run normally" however I am unsure of how to do that and what "tool" they are referring to. If I had to guess the tool is python but im still unsure of how to update it synchronously
  
This project relies on my above-mentioned project
  
So update the dependencies for palworld-server-toolkit in pip as well? Does PalEdit still work though?
 
I know that both PalEdit (https://github.com/EternalWraith/PalEdit) and PalCharacterTransfer (https://github.com/jmkl009/PalworldCharacterTransfer) have been updated on github, but they aren't listed as packages in pip that palworld-server-toolkit uses unlike palworld-save-tools. I'm not sure how those get updated without magicbear updating?

**Comment by seijims** [comment]
I have updated the submodules i.e https://github.com/cheahjs/palworld-save-tools and https://github.com/EternalWraith/PalEdit however if i try to then run python3 palworld_server_toolkit/editor.py I get:
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
I have also tried to run the palworld-save-editor_win_x86_64.exe and that still wont populate the item edit window

**Comment by ZikryZAzhar** [comment]
> I have updated the submodules i.e https://github.com/cheahjs/palworld-save-tools and https://github.com/EternalWraith/PalEdit however if i try to then run python3 palworld_server_toolkit/editor.py I get: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases. I have also tried to run the palworld-save-editor_win_x86_64.exe and that still wont populate the item edit window

Turn off Python on App Execution Aliases
![image](https://github.com/magicbear/palworld-server-toolkit/assets/133621185/2e1f17d7-226a-4917-9c12-c1c65957e995)

**Comment by seijims** [comment]
Now Im getting the following:
PS C:\Users\*acctname*\OneDrive\Desktop\Pal Editor\palworld-server-toolkit> python3 palworld_server_toolkit/editor.py
Traceback (most recent call last):
  File "C:\Users\*acctname*\OneDrive\Desktop\Pal Editor\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 22, in <module>
    import palworld_coord
ModuleNotFoundError: No module named 'palworld_coord'

All this help has been greatly appreciated!
