### ISSUE TITLE
Error parsing CharacterID

### ISSUE THREAD

**Issue by Lu5ck** [magicbear/palworld-server-toolkit#11]
> PlayerUId ←[32m 3e483846-0000-0000-0000-000000000000 ←[0m [InstanceID ←[33m 5fcb1875-c3ec-425f-a221-b304dcc5852c ←[0m] -> Level 27  乃木坂46 Itou Riria
> PlayerUId ←[32m 3fa8e9c1-0000-0000-0000-000000000000 ←[0m [InstanceID ←[33m 36fbe638-8d3b-4372-8597-5f7ca506075c ←[0m] -> Level 50  M4nila
> PlayerUId ←[32m d9f5428f-0000-0000-0000-000000000000 ←[0m [InstanceID ←[33m 1a1a8cd4-5c33-481a-9e91-07888d3333d4 ←[0m] -> Level  9  Anox-ee
> Traceback (most recent call last):
>   File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 3246, in <module>
>   File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 527, in main
>   File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 400, in gui_thread
>   File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1291, in __init__
>   File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1818, in build_gui
>   File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1423, in load_players
>   File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1424, in <listcomp>
>   File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1655, in characterInstanceName
>   File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1635, in getPalTranslatedName
> KeyError: 'CharacterID'
> [25016] Failed to execute script 'editor' due to unhandled exception!

Level.sav at https://gofile.io/d/mPTEd9

**Comment by magicbear** [comment]
Checked, because I think you have cheaters to damage the save:
PlayerUId  59c69b12-0000-0000-0000-000000000000  [InstanceID  1d25ddd8-7427-4903-bd18-adddcbc9ed3c ] -> Level 47  qintil
