### ISSUE TITLE
0.4.2 刪除未引用物品庫會出現以下這個問題閃退

### ISSUE THREAD

**Issue by fallendevil520i** [magicbear/palworld-server-toolkit#13]
<ErrorMessage>LowLevelFatalError [File:D:\works\repos\Pal_SVN\Pal-UE-App\Source\Pal\PalPlayerInventoryData.cpp] [Line: 1643] Cannot Get Container. C, UPalPlayerInventoryData::SetupInventoryMultiHelper_ServerInternal</ErrorMessage>

**Comment by fallendevil520i** [comment]
不太確定是不是檔案大小的問題，在檔案小的時候才成功登入

56.5MB  >> 失敗
54.5MB >> 失敗
50.4MB >> 成功

**Comment by magicbear** [comment]
Fixed on the new version
