### ISSUE TITLE
Clone Character

### ISSUE THREAD

**Issue by vipermushi** [magicbear/palworld-server-toolkit#16]
Hello..not an issue..just want some opinion..I want to clone account so my friend also can get all pal that i have...and use same account with multiple friend in one server but when i try this toolkit yup its working all account can use but one problem...we became sharing pal in that same palbox...let say i take 1 pal in party then use it but my friend can retrieve it back to his pal sphere altough i spawn it..same to other friend..if they throw their pal sphere to spawn..i also can take it back..its like that 1 pal have lots of master..sorry for the bad writing..i dont know how to decsribe..your toolkit was the best..just asking maybe i can edit something using your tools so that we doesnt share pal inventory.

**Comment by magicbear** [comment]
If you use migrate, they will share the pal's, use copy will be create a new containers for the new user.

**Comment by vipermushi** [comment]
Ok i will try..thanks
