### ISSUE TITLE
Migrate Error

### ISSUE THREAD

**Issue by Ikhari** [magicbear/palworld-server-toolkit#21]
I Got this error when try to Migrate using v0.4.8

![image](https://github.com/magicbear/palworld-server-toolkit/assets/72252909/c49927db-f974-42c7-ac0a-445ad77b705c)

![image](https://github.com/magicbear/palworld-server-toolkit/assets/72252909/73b4b247-c44c-4c8f-a0c7-4964847e326c)

**Comment by Ikhari** [comment]
It works using v0.4.7

![image](https://github.com/magicbear/palworld-server-toolkit/assets/72252909/824f1c58-d0f0-4118-b6e7-598617792142)

![image](https://github.com/magicbear/palworld-server-toolkit/assets/72252909/479945e2-d2c2-4fa6-a191-96b648d886bc)

**Comment by Ikhari** [comment]
Okay, there's something weird going on here

Apparently, level, exp, etc does not migrate.

![image](https://github.com/magicbear/palworld-server-toolkit/assets/72252909/16a12fce-fb76-4194-b7f8-4797fedc3147)

When I check ingame, the stats are the same as the old saves, so I'm not sure if it will affect the future save. 

![image](https://github.com/magicbear/palworld-server-toolkit/assets/72252909/b48e1214-e045-4ce0-9247-766de95773ca)

**Comment by magicbear** [comment]
fixed on v0.4.9

**Comment by Ikhari** [comment]
> fixed on v0.4.9

how about this one ?
https://github.com/magicbear/palworld-server-toolkit/issues/21#issuecomment-1936889927
