### ISSUE TITLE
伺服器終端閃退 server crash when log in 

### ISSUE THREAD

**Issue by jerome860227** [magicbear/palworld-server-toolkit#22]
刪除未引用的物品庫後，

架設伺服器的電腦使用新的Level.sav進入遊戲時會導致steamcmd終端直接閃退，並且沒有報錯

**Comment by magicbear** [comment]
请尝试v0.4.9

**Comment by jerome860227** [comment]
仍然會閃退 附上影片

https://github.com/magicbear/palworld-server-toolkit/assets/159606478/433958bc-7007-44e6-887d-9854775026fe

**Comment by jerome860227** [comment]
https://github.com/magicbear/palworld-server-toolkit/assets/159606478/67df66d8-86e9-4828-82ec-c7629ca8d7b8

**Comment by Falke95** [comment]
I have Same Problem.

**Comment by jerome860227** [comment]
感謝作者，我使用v5.1  把Level.sav , LevelMeta.sav , Players 放一起再刪除未引用的物品庫後，成功縮小檔案
