### ISSUE TITLE
my cha no have level

### ISSUE THREAD

**Issue by xczsonn** [magicbear/palworld-server-toolkit#24]
cannot create Struct Rotation
cannot create Struct TowerBossDefeatFlag
cannot create Struct NormalBossDefeatFlag
cannot create Struct PalCaptureCount
cannot create Struct PaldeckUnlockFlag
cannot create Struct RelicObtainForInstanceFlag
cannot create Struct NoteObtainForInstanceFlag
cannot create Struct FastTravelPointUnlockFlag

![image](https://github.com/magicbear/palworld-server-toolkit/assets/12751277/2e264366-69ad-4cbd-a439-583d39182e20)
I tried to migrate a save I created through https://github.com/JannikBirn/palworld-host-save-fix/releases but I don't have a level so it starts 
at 1. Can I fix this?

[7947B324000000000000000000000000.zip](https://github.com/magicbear/palworld-server-toolkit/files/14228398/7947B324000000000000000000000000.zip)

**Comment by magicbear** [comment]
with level.sav
