### ISSUE TITLE
[Feature Request] Prune inactive Guild and its members

### ISSUE THREAD

**Issue by Lu5ck** [magicbear/palworld-server-toolkit#26]
Very recently, I used the "Delete Unreferenced Containers" to trim my sav file from 58mb to 20mb. That not only result in smaller sav file but also resolved rubberbanding so I suspect that rubberbanding is caused by long saving time due to bloated sav file. If that is true then pruning inactive guilds and its members will further reduce sav file size thus improving saving time.

So, I would like to request a feature to prune inactive guilds past user's input time (in hours) and all its related members.

**Comment by magicbear** [comment]
you can just delete all member on the guild, and will be automate delete the guild.
