### ISSUE TITLE
[刪除損壞對象] 這功能會把非角色自行抓捕的寵物變成異常消失

### ISSUE THREAD

**Issue by Supergenli** [magicbear/palworld-server-toolkit#28]
[刪除損壞對象] 這功能會把非角色自行抓捕的寵物變成異常消失（已確定：如通過地上檢的方式獲得的非角色自行抓取的，100%異常消失）
如果在身上的會在隊伍不顯示，在終端機位置會出現一片小白色
無法移動或加入新寵物至有關位置

**Comment by magicbear** [comment]
fix on v0.5.2
