### ISSUE TITLE
转换之后玩家登录出现错误

### ISSUE THREAD

**Issue by GalileoFe** [magicbear/palworld-server-toolkit#3]
环境
windows server 2022
Python版本 = 3.12.1
（确认已关闭服务器）
使用命令
` python -i -m palworld_server_toolkit.editor  "C:\Program Files\steam\steamapps\common\PalServer\Pal\Saved\SaveGames\0\4E385CC444E7933AC657189FCDB94FF3\Level.sav"`
进入交互模式操作

使用migratePlayer合并玩家(从 000001主机到新角色)

合并成功
使用^Z退出python交互模式。

启动服务器之后正常连接，出现

![34d6a7d149ec2ad56480848585473b57](https://github.com/magicbear/palworld-server-toolkit/assets/138156577/c6040815-c292-41ef-859e-fa968c1c8633)
提示。

猜想是部分id没有正确合并。

**Comment by GalileoFe** [comment]
出错的存档
[4E385CC444E7933AC657189FCDB94FF3 - 副本.zip](https://github.com/magicbear/palworld-server-toolkit/files/14157223/4E385CC444E7933AC657189FCDB94FF3.-.zip)

玩家ID 1A9AED96000000000000000000000000
原始ID 00000000000000000000000000000001

**Comment by magicbear** [comment]
合并完成后沒有执行Save()操作
