### ISSUE TITLE
Failed to execute script 'editor' due to unhandled exceptions.

### ISSUE THREAD

**Issue by Isardy** [magicbear/palworld-server-toolkit#30]
Getting the result below when trying to load my save file with the binary editor. 

![image](https://github.com/magicbear/palworld-server-toolkit/assets/9013361/069b5768-c830-4c47-87e8-2d950af1ed3d)

And when running in command line : 

`PS K:\Palworld\96B156A355E44117953D14F63F46ECA6> python -i -m palworld_server_toolkit.editor Level.sav
Loading Level.sav...
Parsing Level.sav...Done in 0.92s.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Python312\Lib\site-packages\palworld_server_toolkit\editor.py", line 3702, in <module>
    main()
  File "C:\Python\Python312\Lib\site-packages\palworld_server_toolkit\editor.py", line 576, in main
    ShowGuild()
  File "C:\Python\Python312\Lib\site-packages\palworld_server_toolkit\editor.py", line 3521, in ShowGuild
    for group_data in wsd['GroupSaveDataMap']['value']:
                      ~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'GroupSaveDataMap'`

**Comment by magicbear** [comment]
try pip install palworld-server-toolkit==0.5.3

**Comment by Isardy** [comment]
`Requirement already satisfied: palworld-server-toolkit==0.5.3 in c:\python\python312\lib\site-packages (0.5.3)
Requirement already satisfied: palworld-save-tools>=0.18.0 in c:\python\python312\lib\site-packages (from palworld-server-toolkit==0.5.3) (0.19.0)
Requirement already satisfied: pillow in c:\python\python312\lib\site-packages (from palworld-server-toolkit==0.5.3) (10.2.0)
Requirement already satisfied: pyperclip in c:\python\python312\lib\site-packages (from palworld-server-toolkit==0.5.3) (1.8.2)`

**Comment by magicbear** [comment]
may be provide your sav file?

**Comment by Isardy** [comment]
[isardyPalworldSave.zip](https://github.com/magicbear/palworld-server-toolkit/files/14230110/isardyPalworldSave.zip)

**Comment by magicbear** [comment]
ERROR: Corrupted Save File
               CharacterSaveParameterMap	15.845 MB	Key: 1791
                       MapObjectSaveData	132.818 MB	Key: 53380833
                  FoliageGridSaveDataMap	68.499 MB	Key: 26507514
         MapObjectSpawnerInStageSaveData	17.049 MB	Key: 7069011
                            WorkSaveData	1.138 MB	Key: 5
                        BaseCampSaveData	0.227 MB	Key: 13
                   ItemContainerSaveData	1195.628 MB	Key: 472137253
                     DynamicItemSaveData	2.589 MB	Key: 1025739
                        GameTimeSaveData	0.000 MB	Key: 2
              DungeonPointMarkerSaveData	0.091 MB	Key: 5
                         DungeonSaveData	0.195 MB	Key: 5

Are this file can be open in game?

**Comment by Isardy** [comment]
The save is from my dedicated server.

Since yesterday, the server crashes when I try to start it; with the crashdump reading :  "SIGSEGV: invalid attempt to write memory at address 0x0000000000000003"

I was hoping your tool, more specifically the "BatchDeleteUnreferencedItemContainers()" tool would fix it.

**Comment by magicbear** [comment]
in fact, your save file is competely damaged. I think may be because of run out of memory, or something wrong, if you didn't have the backup, that is impossible to repair the file. The information for the guild, binding data, reference id, etc.... are losted.

**Comment by Isardy** [comment]
Ha, too bad. Thank you for trying to help.
