### ISSUE TITLE
Binary release non-functional

### ISSUE THREAD

**Issue by Meus-Artis** [magicbear/palworld-server-toolkit#39]
Starting the binary/exe from v0.5.8 just has a console window with the following text: 
```
Traceback (most recent call last):
  File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 45, in <module>
```
There doesn't seem to be any other information other than those 2 lines in the console.

Starting interactive mode with or without the -g flag from the source (python) download works fine, however.

**Comment by trevorjd** [comment]
I just downloaded and used it myself.  I put the exe in the same folder as my level.sav and ran it from there with a double-click.  Took a minute or so then the GUI came up.  It worked fine for me with the "removed containers" option.

**Comment by Meus-Artis** [comment]
> I just downloaded and used it myself. I put the exe in the same folder as my level.sav and ran it from there with a double-click. Took a minute or so then the GUI came up. It worked fine for me with the "removed containers" option. Running on Windows Server 2019.

tried that, saw same error for a tenth of a second before it closed itself
tried dragging the level.sav onto it, and i saw no error, and more lines, looks like it reads up to my players level and name then closes itself

**Comment by Meus-Artis** [comment]
> double click to open and will show a windows for opening the file

I'm not seeing any window other than the console that flashes the error quickly, then closes itself, all in less than half a second.

Dragging the level.sav onto the exe produces this window, that also closes itself instantly.
![explorer_2024-02-12_07-59-13](https://github.com/magicbear/palworld-server-toolkit/assets/4709458/bc516e0a-8c85-4ef3-8654-380ffb971ac0) (IDs censored with white boxes)

When running the py files with "python -i -m palworld_server_toolkit.editor -g [path to level.sav]", it works as expected, but not the .exe
