### ISSUE TITLE
Pal list edit is showing by who captured the Pal not who owns now

### ISSUE THREAD

**Issue by carvalholuan** [magicbear/palworld-server-toolkit#44]
Pal list edit is showing by who captured the Pal not who owns now

**Comment by magicbear** [comment]
Which position are u means for? In paledit? or just select the player and show on the instance

**Comment by carvalholuan** [comment]
paledit, when we choose a player to list the pals

**Comment by magicbear** [comment]
please issue to PalEdit https://github.com/EternalWraith/PalEdit
