### ISSUE TITLE
伺服器使用0.6.1進行刪除營地後發生的問題

### ISSUE THREAD

**Issue by erichuang0704** [magicbear/palworld-server-toolkit#45]
目前不會馬上閃退，長幾個小時後才閃退，短幾十分鐘

然後讀取帕魯資料會失敗，只能讀到少量

請問這樣存檔還能修復嗎? 因為不是馬上閃退所以後續又遊玩了好一段時間

**Comment by magicbear** [comment]
哪個角色讀取失敗？您可以試一試清理无用物品库、清理无用角色库

**Comment by erichuang0704** [comment]
有的，都有清理
但使用修改帕魯功能，只能讀取道些許帕魯 (每個角色都是)，用原版的帕魯修改器也是一樣情形

**Comment by erichuang0704** [comment]
目前又發現，把沒玩的玩家據點刪除後
若該玩家再次加入遊戲，則會使伺服器閃退
