### ISSUE TITLE
Error migrating user from local to server

### ISSUE THREAD

**Issue by KazutoEleros** [magicbear/palworld-server-toolkit#48]
I don't know why but I am getting an error trying to migrate my friend from his single-player to our server
Any ideas?
![image](https://github.com/magicbear/palworld-server-toolkit/assets/21088777/ed76f1c6-2a09-4afa-be5b-f8a516465dde)

**Comment by magicbear** [comment]
may be the save file damaged?

**Comment by KazutoEleros** [comment]
I tested by having my friend make a brand new character on my server, getting them to level 2, having my friend do the same on their computer and then trying to overwrite that new set of characters and still got the same errors.

**Comment by magicbear** [comment]
can u provide the level.sav file that u want to migrate to, and the local level.sav with the players folder?

**Comment by KazutoEleros** [comment]
[20E3655C401C409E2B8978A7811423CC.zip](https://github.com/magicbear/palworld-server-toolkit/files/14301440/20E3655C401C409E2B8978A7811423CC.zip)
[Level.zip](https://github.com/magicbear/palworld-server-toolkit/files/14301444/Level.zip)
Level.zip is the dedicated save, random string of numbers is the single-player data (The character we were trying to migrate is the SP character to their dedicated player file

**Comment by magicbear** [comment]
u may try the lastest version, I think may be u forgot to OpenBackup
