### ISSUE TITLE
Font issue in GUI version

### ISSUE THREAD

**Issue by elementzito** [magicbear/palworld-server-toolkit#49]
Hello! First of all thanks for your awesome tool! Its fast and very cool to use!
Today I upgraded from the old version and I have noticed some issue on Ubuntu LTS, I attach an image.
![Problem](https://github.com/magicbear/palworld-server-toolkit/assets/80927625/62d608f9-8d6d-48aa-87a0-c8cb97b8b563)

I think its font problem, if I click Chinese it shows okay, what is the font used in the project to install it and test?

Thanks!

**Comment by magicbear** [comment]
In the palworld_server_toolkit/assest have a script name font-viewer.py, u may try to open it and found out whats font u have.
