### ISSUE TITLE
是不是把本地房主的存档文件默认识别为了0000000?而不是00001

### ISSUE THREAD

**Issue by davidcrybao** [magicbear/palworld-server-toolkit#5]
![6%N78B{BT~F K5NMOA5CF)D](https://github.com/magicbear/palworld-server-toolkit/assets/25499165/baec65ba-20e8-4112-ad6e-24f7e7fdce73)
![~N(MCF`GQ BJ6H~V_GUVUCJ](https://github.com/magicbear/palworld-server-toolkit/assets/25499165/ada40a75-a49c-4240-9e9b-0e15aba4d8e2)
显示成功,但我去查看players文件夹,里面没有任何文件被修改.
操作非房主玩家的时候能成功.

**Comment by davidcrybao** [comment]
玩家的名字和UID都是不一样的
  45ce2e1c-4426-4cf8-40fb-db95543a177e
  ff9af3a2-4fac-6d74-fa43-7ab968ec47df
  0d0d0a24-42e8-c251-63a5-329109972232
  1134cca1-4532-9b71-cb5b-1d9d939166ee
  793f8210-4bef-02ba-a9b4-1fa6eddd1ce6
  5edff8a8-4d07-f191-fe2c-678bd4d3002a
  aa900688-4e44-e017-d70a-1b822e40eba8
  b3ff8d37-46de-d17f-6216-0d8ef529d0b1

**Comment by magicbear** [comment]
旧版本bug 下最新版即可
