### ISSUE TITLE
trying to fix my save with BatchDeleteUnreferencedItemContainers()

### ISSUE THREAD

**Issue by Rommmmm** [magicbear/palworld-server-toolkit#50]
and getting my task killed every time with this error. is there anything i can do?

Deleting Item Containers: 730000 / 1678769
Deleting Item Containers: 740000 / 1678769
Killed
roman@Roman:/mnt/d/palworld$ /usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 5 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by magicbear** [comment]
you run out of memory, because for BatchDeleteUnreferencedItemContainers, it need to took tons of memory to save all data, u may try to open swap or to a more big memory machine to run the program.
