### ISSUE TITLE
Translate Tool to German

### ISSUE THREAD

**Issue by FunjaPlays** [magicbear/palworld-server-toolkit#51]
Hey Bear,
Thx for the nice Tool 
Is there a way that i can translate it to german for the Github Community ?

**Comment by jkroepke** [comment]
@FunjaPlays I'm not the developer here, but from reading the source:

You have to add

> "de-DE": "Deutsch" 

here: 

https://github.com/magicbear/palworld-server-toolkit/blob/87a8920b8efd25bbae145be889b49f124ce07d79/palworld_server_toolkit/resources/gui.json#L3

Then, copy

- [palworld_server_toolkit/resources/gui_en-US.json](https://github.com/magicbear/palworld-server-toolkit/blob/master/palworld_server_toolkit/resources/gui_en-US.json) -> gui_de-DE.json
- [palworld_server_toolkit/resources/item_en-US.json](https://github.com/magicbear/palworld-server-toolkit/blob/master/palworld_server_toolkit/resources/item_en-US.json) -> item_de-DE.json
- [palworld_server_toolkit/resources/pal_en-US.json](https://github.com/magicbear/palworld-server-toolkit/blob/master/palworld_server_toolkit/resources/pal_en-US.json) -> pal_de-DE.json

and adjust the files.

In case, you are not aware how to fork a repo and setup a Pull Request, just download the files and attach them here...

**Comment by FunjaPlays** [comment]
I use the exe 
U know How to make that to the exe file ?

**Comment by jkroepke** [comment]
In der exe Datei kannst du nicht verändern. Man kann nur die Quell-Daten verändern aus dem Repository hier. Wenn die Dateien hier wieder hochlädt, kann der Entwickler hier wieder eine neue exe erstellen, für alle dann.

**Comment by FunjaPlays** [comment]
Ok alles klar 
Dann werde ich mich mal an die Arbeit machen morgen
