### ISSUE TITLE
Decodeing Failed on Decodeing Path  -> unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by jkroepke** [magicbear/palworld-server-toolkit#53]
I tried the new 0.7.1 which allow to migrate to local.

Migration results into a lot of errors, `Decodeing Failed on Decodeing Path  -> unpack requires a buffer of 4 bytes`

Logs: [log.txt](https://github.com/magicbear/palworld-server-toolkit/files/14303057/log.txt)

Save Game: [6EE886BC41FB3023717E0D9DB323E1C5.zip](https://github.com/magicbear/palworld-server-toolkit/files/14303059/6EE886BC41FB3023717E0D9DB323E1C5.zip)

**Comment by magicbear** [comment]
just ignore it
