### ISSUE TITLE
Migrate to local: pal are cloned

### ISSUE THREAD

**Issue by jkroepke** [magicbear/palworld-server-toolkit#55]
All pals that worked in the bases before migration, are still working inside base + a cloned pal is inside the pal box. In this screen, the both chickens are duplicated.

![image](https://github.com/magicbear/palworld-server-toolkit/assets/1560587/f6ba583c-4819-4c4e-8b7e-5c68a21fcb7d)

How, somehow they may have the same UUID, because the worker symbol from the worked pal is synced with the wal from the box. Including for pals across all bases.

**Comment by magicbear** [comment]
can u provide the file that before migrate and with the uuid for you to migrate?

**Comment by jkroepke** [comment]
Save Game: [6EE886BC41FB3023717E0D9DB323E1C5.zip](https://github.com/magicbear/palworld-server-toolkit/files/14303417/6EE886BC41FB3023717E0D9DB323E1C5.zip)

UUID: A6A3014D000000000000000000000000

**Comment by magicbear** [comment]
fixed on 0.7.2

**Comment by jkroepke** [comment]
Wenn do you plan to release it?

https://github.com/magicbear/palworld-server-toolkit/releases
