### ISSUE TITLE
功能[清理無用角色庫]問題

### ISSUE THREAD

**Issue by Supergenli** [magicbear/palworld-server-toolkit#62]
使用清理無用角色庫的功能時出現附圖情況
![image](https://github.com/magicbear/palworld-server-toolkit/assets/94704373/40b797cf-b295-4710-8153-1a6fe6318add)
已安裝Python 3.12

**Comment by magicbear** [comment]
chk for new ver

**Comment by Supergenli** [comment]
新版v0.75問題仍然存在
![image](https://github.com/magicbear/palworld-server-toolkit/assets/94704373/e64627cf-6050-41b3-b0b8-01f5be31e158)
