### ISSUE TITLE
Possibility to remove corrupted pals

### ISSUE THREAD

**Issue by TracerDS** [magicbear/palworld-server-toolkit#63]
Currently this save editor displays all pals you have. Even corrupted ones (by corrupted I mean pals that you technically have but you cannot interact or see them anywhere). They just live but nothing can be done about it.
By adding the ability to remove pals you can remove these corrupted pals and clean up your base.

Corrupted pals are not even sellable because you cant even select them. In game they dont exist. They exist only on the save file.

**Comment by FunjaPlays** [comment]
Why u dont swap that pal to a new one ?

**Comment by magicbear** [comment]
u can just use repair player feature introduce in 0.7.5

**Comment by TracerDS** [comment]
> u can just use repair player feature introduce in 0.7.5

The `repair player` feature doesn't work all that well in recent patch
![image](https://github.com/magicbear/palworld-server-toolkit/assets/43095317/2f6bf0bf-d981-4dbf-87dd-c933f1478252)
![image](https://github.com/magicbear/palworld-server-toolkit/assets/43095317/d4494b1b-79c2-42f4-b424-7926b521c8f1)

Being able to remove pal individually would be useful not only for corrupted pals but also for cleaning up your base and inventory

**Comment by TracerDS** [comment]
> Why u dont swap that pal to a new one ?

That doesn't change anything. Pal would still be corrupted
