### ISSUE TITLE
2 source transfer

### ISSUE THREAD

**Issue by bordzee** [magicbear/palworld-server-toolkit#64]
Is there a way i could transfer an old level.sav player to new level.sav that has players already?

**Comment by magicbear** [comment]
yes, see the README

**Comment by bordzee** [comment]
Im confuse on the readme instruction.
Heres the flow:
> old level.sav has a player [testplayer]
> [testplayer] transfer to new level.sav (* new level.sav has 20 players) if [testplayer] will transfer it will become 21 players total in the new level.sav
> i transfer the [testplayer].sav in the new server /player folder
> i opened windows GUI server toolkit
> select the new level.sav in the new server
> check the list of the players 
> [testplayer] was not on the list

**much better if there are 2 import files. You can select the first import to be the old level.sav and the 2nd import will be the new level.sav.
