### ISSUE TITLE
Any chance to copy a pal from one player, and paste it onto another?

### ISSUE THREAD

**Issue by JoeUber** [magicbear/palworld-server-toolkit#65]
So I broke my save, and it corrupted it, cannot seem to recover it, one of my users lost his Pal that took him awhile to catch, I tried catching it myself which I did capture it however, I realized there's no way to give it to him. I was wondering if there was a chance we can see this added to this amazing tool.

**Comment by magicbear** [comment]
most easy way is just edit the pal, change the owner player uid, and the slotid to the paste player, and then repair the paste player
