### ISSUE TITLE
功能使用次序

### ISSUE THREAD

**Issue by Supergenli** [magicbear/palworld-server-toolkit#66]
使用功能次序如果不同，會導致TOOLS卡住不動沒有回應
目前發現
使用：修理玩家＞刪除不上線角色＞清理無用物品時＞彈出提示刪除XX件，按確認後> TOOLS卡住不動沒有回應
(CMD窗口不會跳出Delete item containers 數量並進行刪除讀取)

如果使用：修理玩家＞清理無用物品時＞清理無用角色庫＞TOOLS卡住不動沒有回應
(CMD窗口跳出Exeception in Tkinter callback然後就不動)
![image](https://github.com/magicbear/palworld-server-toolkit/assets/94704373/3e99cfe9-5c55-4a05-9905-8fb30c9bfcb9)

**Comment by magicbear** [comment]
可能由於地圖引用層次過深引起，已於0.7.6修復（請下載Source Code運行）
