### ISSUE TITLE
Font issue on Linux

### ISSUE THREAD

**Issue by jeevisonline** [magicbear/palworld-server-toolkit#67]
Hello!

I downloaded the .exe and ran it on Linux, and I am getting a Font issue as shown in the screenshot here.

![image](https://github.com/magicbear/palworld-server-toolkit/assets/97365870/514c35e7-2646-4d48-9edf-1c9884a60321)

I don't submit these often, so let me know if there is anything you want me to try or do on my side to get more information for you.

This is specifically on ZorinOS 16 (Ubuntu 22.04 LTS) using Wine(Or proton, same thing happens)

**Comment by magicbear** [comment]
Can u give me a font list on your os?

**Comment by jeevisonline** [comment]
I have a bunch more fonts on my OS, but I believe Wine by default only gets these.

[fontlist.txt](https://github.com/magicbear/palworld-server-toolkit/files/14323553/fontlist.txt)

If these fonts are no good, I can install the font needed to render it correctly.  Others may have issues with this if they don't install the fonts as well, and don't know how to install new fonts to Wine.

Another option may to be including the font in the .exe?  Or having a separate "Linux" gui ran from flatpak or appimage.

No rush, since CLI works fine through pip.

Thank you for such a great project!

**Comment by magicbear** [comment]
U can edit the gui_en-US.json on the resources to change the default font
