### ISSUE TITLE
服务器存档转本地，等级丢失

### ISSUE THREAD

**Issue by Cp0204** [magicbear/palworld-server-toolkit#68]
使用 GUI v0.7.5，按README操作，服务器存档转本地，角色等级丢失，角色装备都在。

而使用 Palworld Host Save Fix 正常迁移成功。

**Comment by magicbear** [comment]
是否沒有保存？

**Comment by Cp0204** [comment]
> 是否沒有保存？

保存了，试过几次。
一样的结果，存档自动重命名为0000001了，角色装备帕鲁都在，等级0
