### ISSUE TITLE
Clean up unreferenced item containers

### ISSUE THREAD

**Issue by Kakoen** [magicbear/palworld-server-toolkit#7]
In our dedicated server's save file we noticed that item containers used a significant amount of space. So much in fact that the size causes a server crash / loop when it tries to save.

I forked your toolkit and extended it with extra functionality to remove any item containers that are not referenced in the save file and player files. Using that, it shrank our save file from 60 MB to 20 MB, and so far our server is running smoothly (fingers crossed).

The new command I called: `BatchDeleteUnreferencedItemContainers()`

See the changes I made in this diff:
* https://github.com/Kakoen/palworld-server-toolkit/compare/abeb0da..7a2e59b

Maybe it can help you and others! Thank you for making this tool!

**Comment by magicbear** [comment]
Thanks, merged.
