### ISSUE TITLE
点了 清理无用物品库 + 清理无用角色库 + 修复所有玩家后，帕鲁就无法被V举起了

### ISSUE THREAD

**Issue by C-Abner** [magicbear/palworld-server-toolkit#70]
如述

使用版本：release那边下载的 v0.7.5
pal版本：v0.1.4.1
BUG描述：点了 **清理无用物品库 + 清理无用角色库 + 修复所有玩家**后，帕鲁就无法被V举起了。

已测实测1：FIX前存檔可以，FIX后存檔就不能了
已测实测2：FIX后存檔，重新抓一只新帕鲁，是可以V举起的

===============================================
Tool version： v0.7.5 from release download page
Pal version：v0.1.4.1
BUG：After executing **Clean Item + Cleanup Character + Repair All Users** , Pal cannot be Fit by V anymore.

1、Before Clean the sav file is functional. After Clean the sav file becomes non-functional.
2、After applying the Clean and saving, capture a new Pal allows V to fit it again.

**Comment by FunjaPlays** [comment]
Have the Same Problem

**Comment by magicbear** [comment]
the problem has fixed on 0.7.7
