### ISSUE TITLE
修复所有玩家后出现bug

### ISSUE THREAD

**Issue by Kin-Chi** [magicbear/palworld-server-toolkit#72]
使用修复后出现2个bug
1.面板里的帕鲁全部消失，只有身上携带的还保留着。
2.公会标签页中自己的ID为空白。
——————————————————
测试两个玩家，均使用过迁移玩家功能，从4人迁移到多人存档，其中1个使用过迁移到公会功能，另一个没有，两个角色都是单人公会会长，上述bug均存在。修复后GUI均显示Repair success。
——————————————————
[31mDecodeing Failed on Decodeing Path  -> unpack requires a buffer of 4 bytes[0m
[31mDecodeing Failed on Decodeing Path  -> unpack requires a buffer of 4 bytes[0m
Done in 0.43s
Parsing .worldSaveData.ItemContainerSaveData...]0; - 0.0%Done in 9.87s
Parse skipped data in 10.39s
Rebuild Player 2c97ef3b-0000-0000-0000-000000000000 Character Container 986ca142-4170-99cc-6037-76ba77561a1ef0
Error: Player 2c97ef3b-0000-0000-0000-000000000000 Character Container PalStorage 986ca142-4170-99cc-6037-76ba77561a1e Not exists
Warning: Player 2c97ef3b-0000-0000-0000-000000000000 Have character 16 not in containers, loaded: 5 / standby: 356
Error: Guild instance 60c98952-4e23-4fab-fc25-f1a48de5f850 invalid, local items: 362, replace with 41 -> 364
Reload cache
Rebuild Player c847a16b-0000-0000-0000-000000000000 Character Container d6385769-4f13-c527-f91d-378e5dbbfdc1f0
Error: Player c847a16b-0000-0000-0000-000000000000 Character Container PalStorage d6385769-4f13-c527-f91d-378e5dbbfdc1 Not exists
Warning: Player c847a16b-0000-0000-0000-000000000000 Have character 13 not in containers, loaded: 5 / standby: 71
Error: Guild instance 60c98952-4e23-4fab-fc25-f1a48de5f850 invalid, local items: 77, replace with 364 -> 439
Reload cache
Error: Instance ID not matched ba52c98c-4635-4f3f-5aaf-788f74260d5d with save file 10d8a202-4a0d-c100-b492-e38cc15de97f
Duplicate Instance, delete the instance ba52c98c-4635-4f3f-5aaf-788f74260d5d
  Delete Chracater ba52c98c-4635-4f3f-5aaf-788f74260d5d group b5ab6a89-473e-90f1-56f4-da8ca6f95ebc instances
Rebuild Player 1f9dfd04-0000-0000-0000-000000000000 Character Container bbd037cb-4a47-67e3-e2b3-e0a4f2ea0051f0
Error: Player 1f9dfd04-0000-0000-0000-000000000000 Character Container PalStorage bbd037cb-4a47-67e3-e2b3-e0a4f2ea0051 Not exists
Warning: Player 1f9dfd04-0000-0000-0000-000000000000 Have character 26 not in containers, loaded: 5 / standby: 362
Error: Guild instance b5ab6a89-473e-90f1-56f4-da8ca6f95ebc invalid, local items: 368, replace with 313 -> 380
Reload cache

**Comment by magicbear** [comment]
在0.7.6已修正
