### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by treemlt** [magicbear/palworld-server-toolkit#73]
![Untitled](https://github.com/magicbear/palworld-server-toolkit/assets/153841591/78d18ed3-b9fc-4ed4-9137-dfb00f205e63)

Anybody else gets this error with **v0.7.5** ? I'm trying to run _Cleanup Item_ to reduce the _level.sav_ file size 

Tried running it in administrator but still got the same result

**Comment by magicbear** [comment]
Permission error: you are not shutdown the server/game

**Comment by treemlt** [comment]
> Permission error: you are not shutdown the server/game

The SaveGames folder is on my desktop. No game is open... With v0.5.8 it doesn't happen

**Comment by treemlt** [comment]
I found the problem. If you move it to C drive it doesn't give the error.
