### ISSUE TITLE
cant open exe

### ISSUE THREAD

**Issue by xczsonn** [magicbear/palworld-server-toolkit#79]
![image](https://github.com/magicbear/palworld-server-toolkit/assets/12751277/c66a57e5-bde5-407b-b44b-95f83355adb3)

**Comment by armelberango** [comment]
same with me with the latest release

**Comment by Vost02** [comment]
same problem here

**Comment by wycsbg** [comment]
same problem here

**Comment by magicbear** [comment]
fixed on new release binaries file
