### ISSUE TITLE
0.8.0清理無用物品庫 程式會崩潰沒有回應

### ISSUE THREAD

**Issue by YMZ0715** [magicbear/palworld-server-toolkit#82]
![螢幕擷取畫面 2024-02-21 232145](https://github.com/magicbear/palworld-server-toolkit/assets/160757473/f1fe243b-c1c6-4674-9081-437b76f3c34b)
![Uploading 螢幕擷取畫面 2024-02-21 232210.png…]()

**Comment by magicbear** [comment]
loading in the background, or you may try 0.8.1
