### ISSUE TITLE
Version 7.8.x up to 8.1.x are implied to have viruses, based on numerous AV. why?

### ISSUE THREAD

**Issue by supernet2ec** [magicbear/palworld-server-toolkit#87]
My webroot, bitdefender, win11 and win10s defender av, googles anti virus, nortons antivirus, synologys web anti virus, acronis cyber anti virus w/ai assist have flagged versions 7.9.x up to version 8.1.x with this malicious virus "trojan Wacatac.B!ml. ". Dude why? i run my stuff in VM containers and through linux. Thankfully, but why would you do this? Even the source implies its viral when scanned. Can you explain the reasoning behind so many anti virus engines flagging this, even flagship AVs?

**Comment by FunjaPlays** [comment]
Bro its Like any other keygen or Patch / Crack Programm u can use 
It always says that its an Virus 
No Need to be Panic

**Comment by magicbear** [comment]
The packing for python problem, you can download python manually

**Comment by supernet2ec** [comment]
I have python installed version 1.10.x up to 1.12.x already. Alright thanks for the answer,
