### ISSUE TITLE
[Request] Edit maximum base count per guild

### ISSUE THREAD

**Issue by WindedHero** [magicbear/palworld-server-toolkit#89]
For dedicated server setups it does not seem to matter what you set in PalworldSettings.ini, the maximum workers and maximum guild count are tied to the level.sav
Would like to be able to edit these options in level.sav somehow

**Comment by AbsconditusOne** [comment]
This setting is set using worldoption.sav, and are not read from palworldsettings.ini

**Comment by WindedHero** [comment]
WorldOption.Sav is not applicable for dedicated servers. That file is only found in local saves.
