### ISSUE TITLE
[Suggestion] In-game coordinates of base camps

### ISSUE THREAD

**Issue by bostrt** [magicbear/palworld-server-toolkit#93]
Hello, this toolkit has been so helpful for a couple servers I manage. Thank you for creating it!

I have a suggestion on for `ShowGuilds()` which is to include the in-game coordinates of base camps. Me and @cmkb3 managed to reverse engineer the coordinates and have documented it here:

https://github.com/palworldlol/palworld-coord/

If you want to include this in your toolkit: the two functions in https://github.com/palworldlol/palworld-coord/blob/main/src/palworld_coord/__init__.py are very small and I have used a permissive license so feel free to copy them instead of adding a new dependency to your project.

**Comment by magicbear** [comment]
add on 0.8.5
