### ISSUE TITLE
Migrate to local  Error 

### ISSUE THREAD

**Issue by wycsbg** [magicbear/palworld-server-toolkit#94]
Error prompt： “WARNING : Error: Invalid Equal Item Container ID 5b7f1cca-4deb-e98f-cfb7-43bda86afefc”

**Comment by 1299897460** [comment]
使用源码编译即可 0.8.4 并未编译成二进制




?
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "magicbear/palworld-server-toolkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月1日(星期五) 晚上8:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[magicbear/palworld-server-toolkit] Migrate to local  Error  (Issue #94)





 
Error prompt： “WARNING : Error: Invalid Equal Item Container ID 5b7f1cca-4deb-e98f-cfb7-43bda86afefc”
