### ISSUE TITLE
Detecting as Trojan on Windows 11

### ISSUE THREAD

**Issue by xiaden** [magicbear/palworld-server-toolkit#96]
Specifically flagging as Trojan:Win32/Znyonm from latest build.

**Comment by Zyletron** [comment]
> Specifically flagging as Trojan:Win32/Znyonm from latest build.

Same

**Comment by magicbear** [comment]
You can download the source or run by pip, binary packed by pyinstaller, maybe mistake for virus software

**Comment by Testerac5** [comment]
Just fyi, I get a trojan false alert when i pack projects to binary with pyinstaller. there is 100% nothing to be concerned of here for anyone who searches thru the issues in the future.
