### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by xczsonn** [magicbear/palworld-server-toolkit#97]
![image](https://github.com/magicbear/palworld-server-toolkit/assets/12751277/b64c043e-28e3-4783-a242-eac07702638e)
All functions, such as clean up item, repair all player, are not working.

**Comment by magicbear** [comment]
your player save file is invalid

**Comment by xczsonn** [comment]
how to fix it? Everything is working fine in game.

**Comment by Bibo89** [comment]
same error but in the same saves made an hour before it worked
